
@baseUrl=http://localhost:3030

### OBS. ändra då du använder den slutliga databasen:
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTU3NTFlYWQ3NWYxNzg5M2JjZWM0NzMiLCJlbWFpbCI6ImtyYWFrYW5Aa3Jha21haWwuY29tIiwiaWF0IjoxNjM0MDY4MjMwLCJleHAiOjE2MzY2NjAyMzB9.VpnFgaOfbcpkHVOYQbRDp6q3VCAWo8uZGn8htEsO_bU
GET {{baseUrl}}

### Registrera en ny användare
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Kråkan",
    "surname": "Kråkanson",
    "email": "kraakaan@krakmaill.com",
    "password": "hejhej123"

}

### Logga in 
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "kraakan@krakmail.com",
    "password": "hejhej123"
}

### Annonsera en ny stuga
POST {{baseUrl}}/cabins
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "owner": "Drew Goddard",
    "address": "in the woods",
    "size": 30,
    "sauna": false,
    "beach": false,
    "price": 5

}

### Hämta egna stugor
GET {{baseUrl}}/cabins/owned
Content-Type: application/json
Authorization: Bearer {{token}}


### Hämta alla stugor
GET {{baseUrl}}/cabins
Authorization: Bearer {{token}}

### Hämta en viss stuga, inkl. bokningar

GET {{baseUrl}}/cabins/615752529434c05f1199b1a9
Content-Type: application/json
Authorization: Bearer {{token}}

### Boka en stuga -- om stugan inte är ledig på den givna tiden returneras datumen för de överlappande boknignarna
POST {{baseUrl}}/bookings/615752529434c05f1199b1a9
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "arrivalDate": "2021-09-30T10:32:09.146Z",
    "departureDate": "2021-09-30T11:26:56.392Z"
}

### Ändra hela objektet med PUT 
PUT {{baseUrl}}/cabins/615752529434c05f1199b1a9
### Hämta alla bokningar
GET {{baseUrl}}/bookings
Authorization: Bearer {{token}}

### Avboka 
DELETE {{baseUrl}}/bookings/6157389f68bca1999e22d7fd
Authorization: Bearer {{token}}

### Ändra sin bokning 
PUT {{baseUrl}}/bookings/6157389f68bca1999e22d7fd
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "arrivalDate": "2021-01-01",
    "departureDate": "2023-12-12"
}


### Ändra sitt stugobjekt, med PUT 
PUT {{baseUrl}}/cabins/615731fed16595269a4d721e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "owner": "kraakan@krakmail.com",
    "address": "in the woods",
    "size": 20,
    "sauna": true,
    "beach": true,
    "price": 2
}

### Ändra enskilt värde i sin stuga,  med PATCH 
PATCH {{baseUrl}}/cabins/615731fed16595269a4d721e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "size": 999,
    "beach": false
}


### Radera sin stuga 
DELETE {{baseUrl}}/cabins/615731fed16595269a4d721e
Authorization: Bearer {{token}}

### Hämta stugorna som användaren äger
 GET {{baseUrl}}/cabins/owned
Authorization: Bearer {{token}}

