
@baseUrl=http://localhost:3030

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTU3NDBkOWY0MGY3ZDYzNWVlMDU5ODkiLCJlbWFpbCI6IkxhcmFAZ21haWwuY29tIiwiaWF0IjoxNjMzMTA4MTk3LCJleHAiOjE2MzgyOTIxOTd9.AQqRt43Gk1CEavl0FYp3VvH4lrF_As05SLNwmGkc60U

### Registrera en ny användare
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Lara",
    "surname": "Vikman",
    "email": "Lara@gmail.com",
    "password": "hejhej123"

}

### Logga in 
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "Lara@gmail.com",
    "password": "hejhej123"
}


### Annonsera en ny stuga
POST {{baseUrl}}/cabins
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "owner": "Dilan",
    "address": "in the house",
    "size": 310,
    "sauna": true,
    "beach": true,
    "price": 50

}

### Hämta alla stugor
GET {{baseUrl}}/cabins
Authorization: Bearer {{token}}


### Boka en stuga 
POST {{baseUrl}}/bookings/615731fed16595269a4d721e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "arrivalDate": "2021-09-30",
    "departureDate": "2021-10-30"
}

### Hämta alla bokningar
GET {{baseUrl}}/bookings
Authorization: Bearer {{token}}

### Avboka 
DELETE {{baseUrl}}/bookings/6157310892f9321123684a3c
Authorization: Bearer {{token}}

### Ändra sin bokning 
PUT {{baseUrl}}/bookings/6157389f68bca1999e22d7fd
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "arrivalDate": "2021-01-01",
    "departureDate": "2025-12-12"
}


### Ändra en stuga, hela objektet med PUT 
PUT {{baseUrl}}/cabins/615731fed16595269a4d721e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "owner": "Jonas@gmail.com",
    "address": "in the woods",
    "size": 2,
    "sauna": true,
    "beach": false,
    "price": 200
}

### Ändra enskilt värde i en stuga, med PATCH 
PATCH {{baseUrl}}/cabins/6157329ed16595269a4d7221
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "size": 999,
    "beach": false
}


### Radera en stuga 
DELETE {{baseUrl}}/cabins/6157329ed16595269a4d7221
Authorization: Bearer {{token}}




