
@baseUrl = http://localhost:3030
// OBS. ändra då du använder den slutliga databasen:
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTU1N2NhZjUzYWJmNTY5YmY5NGU0MGEiLCJlbWFpbCI6IkRpbGFuQGdtYWlsLmNvbW0iLCJpYXQiOjE2MzMwMDAwOTMsImV4cCI6MTYzNTU5MjA5M30.ZwOp6Am1S_hQnx2plBToHA2cTraTLB9ybIceWfRlCVE
GET {{baseUrl}}

### Regisrera en ny användare

POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Dilan",
    "surname": "Ledeon",
    "email": "Dilan@gmail.comm",
    "password": "hejhej123"

}

### Logga in 

POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "email": "Dilan@gmail.comm",
    "password": "hejhej123"
}

### Annonsera en ny stuga

POST {{baseUrl}}/cabins
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "renter": "Drew Goddard",
    "address": "in the woods",
    "size": 30,
    "sauna": false,
    "beach": false,
    "price": 5

}

### Hämta stugor

GET {{baseUrl}}/cabins
Authorization: Bearer {{token}}